// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AlertController from "./alert_controller"
application.register("alert", AlertController)

import FieldController from "./field_controller"
application.register("field", FieldController)

import FocusOnErrorController from "./focus_on_error_controller"
application.register("focus-on-error", FocusOnErrorController)

import PiechartController from "./piechart_controller"
application.register("piechart", PiechartController)

import ProfileController from "./profile_controller"
application.register("profile", ProfileController)

import RemovalsController from "./removals_controller"
application.register("removals", RemovalsController)

import TimerController from "./timer_controller"
application.register("timer", TimerController)

import togglePasswordController from "./toggle_password_controller";
application.register("toggle-password", togglePasswordController);
